// ExportManager.js – All file-export operations
// Includes PNG, SVG, CSV, JSON, and Interactive HTML export

export class ExportManager {
  constructor(renderer, data) {
    this._renderer = renderer;
    this._data = data;
  }

  exportSVG() {
    const str = this._renderer.getSVGString();
    this._download(`radar_${this._ts()}.svg`, str, 'image/svg+xml;charset=utf-8');
  }

  exportPNG(scale = 2) {
    const svgStr = this._renderer.getSVGString();
    const svg = this._renderer.svg;
    const W = Number(svg.getAttribute('width')) * scale;
    const H = Number(svg.getAttribute('height')) * scale;

    const blob = new Blob([svgStr], { type: 'image/svg+xml;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const img = new Image();

    img.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = W;
      canvas.height = H;
      const ctx = canvas.getContext('2d');
      ctx.fillStyle = getComputedStyle(document.documentElement)
        .getPropertyValue('--bg').trim() || '#060c14';
      ctx.fillRect(0, 0, W, H);
      ctx.drawImage(img, 0, 0, W, H);
      canvas.toBlob(pngBlob => {
        const a = document.createElement('a');
        a.href = URL.createObjectURL(pngBlob);
        a.download = `radar_${this._ts()}.png`;
        a.click();
        URL.revokeObjectURL(a.href);
      }, 'image/png');
      URL.revokeObjectURL(url);
    };
    img.onerror = () => URL.revokeObjectURL(url);
    img.src = url;
  }

  exportCSV() {
    this._download(`radar_data_${this._ts()}.csv`, this._data.toCSV(), 'text/csv;charset=utf-8');
  }

  exportJSON() {
    this._download(`radar_data_${this._ts()}.json`, this._data.toJSON(), 'application/json');
  }

  exportInteractiveHTML() {
    const svgStr = this._renderer.getSVGString();
    const data = this._data;
    const labels = data.labels;
    const datasets = data.datasets;
    const title = data.title || 'RadarViz Pro Report';
    const subtitle = data.subtitle || '';

    const tableRows = labels.map((label, i) => {
      const cells = datasets.map(d => `<td>${this._escape(d.values[i] ?? 0)}</td>`).join('');
      return `<tr><td><strong>${this._escape(label)}</strong></td>${cells}</tr>`;
    }).join('');

    const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>RadarViz Pro Report</title>
  <style>
    * { box-sizing: border-box; }
    body {
      font-family: 'Syne', -apple-system, sans-serif;
      background: #eef2f7;
      margin: 0;
      padding: 24px;
    }
    .container {
      max-width: 1300px;
      margin: 0 auto;
      background: white;
      border-radius: 24px;
      box-shadow: 0 12px 32px rgba(0,0,0,0.1);
      padding: 24px;
    }
    h1 { font-size: 1.8rem; margin: 0 0 0.25rem 0; color: #0d1e2c; }
    .sub { color: #3a6080; margin-bottom: 24px; }
    svg {
      width: 100%;
      height: auto;
      background: white;
      border-radius: 16px;
      border: 1px solid #e0e6ed;
      margin: 16px 0;
    }
    h2 { font-size: 1.4rem; margin: 24px 0 12px 0; color: #0d1e2c; }
    .table-wrapper {
      overflow-x: auto;
      border-radius: 16px;
      border: 1px solid #e0e6ed;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      font-size: 0.85rem;
    }
    th, td {
      padding: 10px 12px;
      text-align: center;
      border-bottom: 1px solid #e0e6ed;
    }
    th {
      background: #f5f7fa;
      font-weight: 700;
      color: #1f3a4c;
      cursor: pointer;
      user-select: none;
      position: sticky;
      top: 0;
    }
    th:hover { background: #e6edf4; }
    td:first-child, th:first-child {
      position: sticky;
      left: 0;
      background: white;
      font-weight: 600;
      color: #0969da;
    }
    th:first-child { background: #f5f7fa; }
    .credit {
      text-align: center;
      margin-top: 32px;
      font-size: 0.75rem;
      color: #6c86a3;
      border-top: 1px solid #e0e6ed;
      padding-top: 20px;
    }
    .sort-icon { margin-left: 6px; font-size: 0.7rem; }
  </style>
</head>
<body>
<div class="container">
  <h1>${this._escape(title)}</h1>
  ${subtitle ? `<div class="sub">${this._escape(subtitle)}</div>` : ''}
  ${svgStr}
  <h2>Data Table</h2>
  <div class="table-wrapper">
    <table id="dataTable">
      <thead>
        <tr>
          <th>Axis</th>
          ${datasets.map(d => `<th>${this._escape(d.name)}</th>`).join('')}
        </tr>
      </thead>
      <tbody>
        ${tableRows}
      </tbody>
    </table>
  </div>
  <div class="credit">
    Generated by RadarViz Pro · Developed by Mohd Zulhairy, 2026
  </div>
</div>
<script>
  (function() {
    const getCellValue = (row, idx) => row.cells[idx].innerText;
    const comparer = (idx, asc) => (a, b) => {
      const aVal = getCellValue(a, idx);
      const bVal = getCellValue(b, idx);
      const numA = parseFloat(aVal);
      const numB = parseFloat(bVal);
      if (!isNaN(numA) && !isNaN(numB)) {
        return asc ? numA - numB : numB - numA;
      }
      return asc ? aVal.localeCompare(bVal) : bVal.localeCompare(aVal);
    };
    document.querySelectorAll('#dataTable th').forEach((th, idx) => {
      th.addEventListener('click', () => {
        const table = document.getElementById('dataTable');
        const tbody = table.tBodies[0];
        const rows = Array.from(tbody.rows);
        const isAsc = th.classList.contains('asc');
        rows.sort(comparer(idx, !isAsc));
        rows.forEach(row => tbody.appendChild(row));
        document.querySelectorAll('#dataTable th').forEach(h => h.classList.remove('asc', 'desc'));
        th.classList.add(isAsc ? 'desc' : 'asc');
      });
    });
  })();
</script>
</body>
</html>`;
    this._download(`radar_report_${this._ts()}.html`, html, 'text/html');
  }

  // ── Private helpers ──────────────────────────────────────────
  _download(filename, content, mime) {
    const a = Object.assign(document.createElement('a'), {
      href: URL.createObjectURL(new Blob([content], { type: mime })),
      download: filename,
    });
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(a.href);
  }

  _ts() {
    const d = new Date();
    return [
      d.getFullYear(),
      String(d.getMonth() + 1).padStart(2, '0'),
      String(d.getDate()).padStart(2, '0'),
      '_',
      String(d.getHours()).padStart(2, '0'),
      String(d.getMinutes()).padStart(2, '0'),
    ].join('');
  }

  _escape(s = '') {
    return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  }
}